apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
  - port: 9002
    nodePort: 30123
    targetPort: 9002
    protocol: TCP
  type: NodePort
  selector:
    app: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image:  {IMAGE_URL}:{IMAGE_TAG}
        name: test
        imagePullPolicy: Never
        ports:
        - containerPort: 9002